version: '3.7'

services:
  server:
    build: .
    container_name: sf_server
    env_file:
      - .env
    volumes:
      - .:/app
    entrypoint: python src/main.py
    ports:
      - "8000:8000"

