version: '3.7'

services:
  server:
    build: .
    container_name: sf_server
    env_file:
      - .env
    volumes:
      - .:/app
      - /home/sf/media:/home/media
    entrypoint: python src/main.py
    ports:
      - "8080:8000"

