"""add name field

Revision ID: 7037f95f1d15
Revises: dc83ac2a00cd
Create Date: 2023-03-27 02:09:52.388634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7037f95f1d15'
down_revision = 'dc83ac2a00cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('name', sa.String(length=127), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claims', 'name')
    # ### end Alembic commands ###
